### ISSUE TITLE
Call to Journal endpoint to get DSFinV-K export as .ZIP file doesn't work

### ISSUE THREAD

**Issue by AndreasEntscheffPinter** [fiskaltrust/product-de-bring-your-own-datacenter#33] opened 2021-02-23 12:01 UTC
In this https://github.com/fiskaltrust/product-de-bring-your-own-datacenter/issues/26#issuecomment-745380711 @TSchmiedlechner pointed out, that the Journal endpoint returns a default JSON object that has the meaning, that the middleware couldn't parse the ftJournalType.  
Here's a screenshot of the postman-request that illustrates the issue:  
![image](https://user-images.githubusercontent.com/73586974/108840298-70273180-75d6-11eb-872b-6e9501b6d2b0.png)  
  
I tried all variants of ftJournalType, sending it in decimal, hex, octal: It's always returning the same result.  
 I also tried the other possible values for ftJournalType as described [here](https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/reference-tables/type-of-journal-ftjournaltype.html) but that doesn't change anything.  
  
I now tried upgrading byodc to version 1.3.12-rc1-buster, but this didn't help. The only thing that changed is that I get the response now in plaintext instead of array of ascii-codes.  
  
Please fix the DSFinV-K export (or did I use the middleware wrongly?). Maybe you need the cashbox-id I'm working with, it is: 23ca4176-7c93-40ae-8a15-ab2b1276c522

**Comment by TSchmiedlechner** [comment] 2021-02-26 13:00
Hi @AndreasEntscheffPinter!
This behavior has changed and is now equal to the local Middleware: the `type` needs to be passed as a request parameter now, e.g.
- DSFinV-K: `/json/journal?type=4919338167972134914&from=0&to=10000`
- TAR (from MW): `/json/journal?type=4919338167972134915&from=0&to=10000`

Sorry for the confusion, I think this should now also be displayed correctly at the `/swagger` endpoint.

**Comment by AndreasEntscheffPinter** [comment] 2021-03-16 09:01
@TSchmiedlechner  
Thanks for your reply!  
  
Good is: Now I don't get any errors from the request and it gives me HTTP-status 200 OK.  
  
Unfortunately I don't get any data returned, the response is empty.  
I already signed 7 receipts in total using the fiskaltrust middleware. I checked, if they really went into the middlewares database by directly checking in the database -> see this [screenshot](https://user-images.githubusercontent.com/73586974/111281537-54470680-863d-11eb-9288-02b4326427e6.png)  
  
Maybe I have a misunderstanding in what the DSFinV-K actually is? From my understanding it is a journal where all activity of the cashregister is tracked and it's probably encrypted. Very similar to the austrian DEP journal.  
So I expected if I have signed 7 receipts I should see this in the DSFinV-K journal, isn't it?  

I played around a bit with the `from` and `to` parameter, used 0 for both or 637501937600940858 for the to-parameter (this is the current max value of `ftReceiptMoment` in the `ftReceiptJournal` table) - but the DSFinV-K request always returns empty data.  
  
Please let me know what's wrong, thank you :slightly_smiling_face:

**Comment by TSchmiedlechner** [comment] 2021-03-23 15:38
Hi @AndreasEntscheffPinter,
my apologies for the late response! Great that the API is working as expected now. 🙂 

I think the empty response is caused by the absence of a daily-closing receipt, is this possible? The DSFinV-K is based on those (i.e. "Kassenabschlüsse" in German), and if no receipt of this type was made yet, the response will be empty. To workaround this, please use the following receipt: https://middleware-samples.docs.fiskaltrust.cloud/#6e241154-0e76-4bd0-b00d-4471415e6a76

**Comment by AndreasEntscheffPinter** [comment] 2021-03-24 09:59
Hello @TSchmiedlechner!   
  
> I think the empty response is caused by the absence of a daily-closing receipt   
  
Yes, this was the problem 🙂 Thank you for info!  
Now the export is working as expected. I'm receiving binary data and the result is a zip-file that I'm able to open, content looks okay 👍

**Comment by TSchmiedlechner** [comment] 2021-03-24 10:41
Perfect, great to hear that! I'm happy we could help, closing this now. Feel free to reach out if you encounter any more questions 🙂

**Closed by TSchmiedlechner** 2021-03-24 10:41 UTC
Labels: bug
